In [1]:
import numpy as np

In [4]:
# Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [8]:
# Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
a1 = a.reshape(3,4)
a2 = a.reshape(2,6)
a3 = a.reshape(3,4)
a4 = a.reshape(6,2)
a5 = a.reshape(4,3)


In [13]:
#Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 
#(в трех примерах - для обозначения числа столбцов, в двух - для строк).
b1 = np.reshape(a,(3,-1))
b2 = np.reshape(a,(2,-1))
b3 = np.reshape(a,(4,-1))
b4 = np.reshape(a,(-1,3))
b5 = np.reshape(a,(-1,2))

In [14]:
# Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
# Нет, одномерный массив имеет размерность 1, 12, где 1 - кол-во строк и 12 - кол-во столбцов. 

In [22]:
# Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального 
#распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива
#одномерный массив с таким же атрибутом size, как и исходный массив.
x = np.random.randn(3,4)
y = x.flatten()


(12,)

In [32]:
# Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [33]:
# Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
#В чем разница между массивами a и b?

b=np.arange(20, 1, -2).reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [34]:
#Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
#чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [40]:
b=np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
v = np.vstack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [50]:
# Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, 
#чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. 
#Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с 
#помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?
a = np.arange(0,12)
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [55]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [57]:
B.shape

(4, 4)

In [58]:
B_inv=np.linalg.inv(B)
B_inv


LinAlgError: Singular matrix

In [59]:
# Инициализируйте генератор случайных числе с помощью объекта seed, равного 42
np.random.seed(42)

In [60]:
# Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых 
#чисел от 0 до 16 невключительно. 
c=np.random.randint(0, 16,16)
c


array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [62]:
# Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из 
#предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.
C = c.reshape(4,4)
D = B + C*10


In [63]:
d=np.linalg.det(D)
d

-28511999.999999944

In [64]:
r=np.linalg.matrix_rank(D)
r

4

In [65]:
D_inv=np.linalg.inv(D)
D_inv


array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [66]:
# Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv 
# остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C
#- в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент 
#матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых 
#соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.
D_inv=np.where(D_inv<0, 0,1)
D_inv



array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [67]:
print(B)
print(C)
E=np.where(D_inv==1, B, C)
E

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])